[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "api/functions/"

[context.production.environment]
SHOPIFY_STOREFRONT_API_TOKEN="2bb50f3d6ad3216ff1fa3f316d195270"
SHOPIFY_API_ENDPOINT="https://timelifefitness.myshopify.com/api/unstable/graphql.json"
NEXT_PUBLIC_ALGOLIA_API_KEY="cb4894b0dd752c34ce8748d79c11021686585553a65841f5e8ba26c8705e60b7"
NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY="3a89a9c31ea536f9ed2c2034f5f899c8"
NEXT_PUBLIC_ALGOLIA_APP_ID="PVXTT5VWPI"
NEXT_PUBLIC_ALGOLIA_BASE_URL="https://crawler.algolia.com"
NEXT_PUBLIC_STRIPE_SECRET_KEY="pk_test_51K6pNiIbxjeJD6w8gGJPrnLyazHXKV29Bkb6skmIOCz8vYaj7Yltdm0l1qEYGYMWKcDhMFEIkaogka4B1mzZWgrL007pzDKPta"

[context.deploy-preview.environment]
SHOPIFY_STOREFRONT_API_TOKEN="2bb50f3d6ad3216ff1fa3f316d195270"
SHOPIFY_API_ENDPOINT="https://timelifefitness.myshopify.com/api/unstable/graphql.json"
NEXT_PUBLIC_ALGOLIA_API_KEY="cb4894b0dd752c34ce8748d79c11021686585553a65841f5e8ba26c8705e60b7"
NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY="3a89a9c31ea536f9ed2c2034f5f899c8"
NEXT_PUBLIC_ALGOLIA_APP_ID="PVXTT5VWPI"
NEXT_PUBLIC_ALGOLIA_BASE_URL="https://crawler.algolia.com"
NEXT_PUBLIC_STRIPE_SECRET_KEY="pk_test_51K6pNiIbxjeJD6w8gGJPrnLyazHXKV29Bkb6skmIOCz8vYaj7Yltdm0l1qEYGYMWKcDhMFEIkaogka4B1mzZWgrL007pzDKPta"
